
# Integers
VP_AVATAR_SESSION = 0
VP_AVATAR_TYPE = 1
VP_MY_TYPE = 2
VP_OBJECT_ID = 3
VP_OBJECT_TYPE = 4
VP_OBJECT_TIME = 5
VP_OBJECT_USER_ID = 6
VP_WORLD_STATE = 7
VP_WORLD_USERS = 8
VP_REFERENCE_NUMBER = 9
VP_CALLBACK = 10
VP_USER_ID = 11
VP_USER_REGISTRATION_TIME = 12
VP_USER_ONLINE_TIME = 13
VP_USER_LAST_LOGIN = 14
VP_FRIEND_ID = 15
VP_FRIEND_USER_ID = 16
VP_FRIEND_ONLINE = 17
VP_MY_USER_ID = 18
VP_PROXY_TYPE = 19
VP_PROXY_PORT = 20
VP_CELL_X = 21
VP_CELL_Z = 22
VP_TERRAIN_TILE_X = 23
VP_TERRAIN_TILE_Z = 24
VP_TERRAIN_NODE_X = 25
VP_TERRAIN_NODE_Z = 26
VP_TERRAIN_NODE_REVISION = 27
VP_CLICKED_SESSION = 28
VP_CHAT_TYPE = 29
VP_CHAT_COLOR_RED = 30
VP_CHAT_COLOR_GREEN = 31
VP_CHAT_COLOR_BLUE = 32
VP_CHAT_EFFECTS = 33
VP_DISCONNECT_ERROR_CODE = 34
VP_URL_TARGET = 35
VP_CURRENT_EVENT = 36
VP_CURRENT_CALLBACK = 37
VP_CELL_REVISION = 38
VP_CELL_STATUS = 39
VP_JOIN_ID = 40

# Floats
VP_AVATAR_X = 0
VP_AVATAR_Y = 1
VP_AVATAR_Z = 2
VP_AVATAR_YAW = 3
VP_AVATAR_PITCH = 4
VP_MY_X = 5
VP_MY_Y = 6
VP_MY_Z = 7
VP_MY_YAW = 8
VP_MY_PITCH = 9
VP_OBJECT_X = 10
VP_OBJECT_Y = 11
VP_OBJECT_Z = 12
VP_OBJECT_ROTATION_X = 13
VP_OBJECT_ROTATION_Y = 14
VP_OBJECT_ROTATION_Z = 15
VP_OBJECT_YAW = VP_OBJECT_ROTATION_X = 16
VP_OBJECT_PITCH = VP_OBJECT_ROTATION_Y = 17
VP_OBJECT_ROLL = VP_OBJECT_ROTATION_Z = 18
VP_OBJECT_ROTATION_ANGLE = 19
VP_TELEPORT_X = 20
VP_TELEPORT_Y = 21
VP_TELEPORT_Z = 22
VP_TELEPORT_YAW = 23
VP_TELEPORT_PITCH = 24
VP_CLICK_HIT_X = 25
VP_CLICK_HIT_Y = 26
VP_CLICK_HIT_Z = 27
VP_JOIN_X = 28
VP_JOIN_Y = 29
VP_JOIN_Z = 30
VP_JOIN_YAW = 31
VP_JOIN_PITCH = 32

# Strings
VP_AVATAR_NAME = 0
VP_CHAT_MESSAGE = 1
VP_OBJECT_MODEL = 2
VP_OBJECT_ACTION = 3
VP_OBJECT_DESCRIPTION = 4
VP_WORLD_NAME = 5
VP_USER_NAME = 6
VP_USER_EMAIL = 7
VP_WORLD_SETTING_KEY = 8
VP_WORLD_SETTING_VALUE = 9
VP_FRIEND_NAME = 10
VP_PROXY_HOST = 11
VP_TELEPORT_WORLD = 12
VP_URL = 13
VP_JOIN_WORLD = 14
VP_JOIN_NAME = 15
VP_START_WORLD = 16

# Events
VP_EVENT_CHAT = 0
VP_EVENT_AVATAR_ADD = 1
VP_EVENT_AVATAR_CHANGE = 2
VP_EVENT_AVATAR_DELETE = 3
VP_EVENT_OBJECT = 4
VP_EVENT_OBJECT_CHANGE = 5
VP_EVENT_OBJECT_DELETE = 6
VP_EVENT_OBJECT_CLICK = 7
VP_EVENT_WORLD_LIST = 8
VP_EVENT_WORLD_SETTING = 9
VP_EVENT_WORLD_SETTINGS_CHANGED = 10
VP_EVENT_FRIEND = 11
VP_EVENT_WORLD_DISCONNECT = 12
VP_EVENT_UNIVERSE_DISCONNECT = 13
VP_EVENT_USER_ATTRIBUTES = 14
VP_EVENT_CELL_END = 15
VP_EVENT_TERRAIN_NODE = 16
VP_EVENT_AVATAR_CLICK = 17
VP_EVENT_TELEPORT = 18
VP_EVENT_URL = 19
VP_EVENT_OBJECT_BUMP_BEGIN = 20
VP_EVENT_OBJECT_BUMP_END = 21
VP_EVENT_TERRAIN_NODE_CHANGED = 22
VP_EVENT_JOIN = 23

# Chat types
VP_CHAT_NORMAL = 0
VP_CHAT_CONSOLE_MESSAGE = 1
VP_CHAT_PRIVATE = 2

# Return Codes
VP_RC_SUCCESS = 0
VP_RC_VERSION_MISMATCH = 1
VP_RC_NOT_INITIALIZED = 2
VP_RC_ALREADY_INITIALIZED = 3
VP_RC_STRING_TOO_LONG = 4
VP_RC_INVALID_LOGIN = 5
VP_RC_WORLD_NOT_FOUND = 6
VP_RC_WORLD_LOGIN_ERROR = 7
VP_RC_NOT_IN_WORLD = 8
VP_RC_CONNECTION_ERROR = 9
VP_RC_NO_INSTANCE = 10
VP_RC_NOT_IMPLEMENTED = 11
VP_RC_NO_SUCH_ATTRIBUTE = 12
VP_RC_NOT_ALLOWED = 13
VP_RC_DATABASE_ERROR = 14
VP_RC_NO_SUCH_USER = 15
VP_RC_TIMEOUT = 16
VP_RC_NOT_IN_UNIVERSE = 18
VP_RC_INVALID_ARGUMENTS = 19
VP_RC_OBJECT_NOT_FOUND = 20
VP_RC_UNKNOWN_ERROR = 21
VP_RC_RECURSIVE_WAIT = 22
VP_RC_JOIN_DECLINED = 23
VP_RC_SECURE_CONNECTION_REQUIRED = 24
VP_RC_HANDSHAKE_FAILED = 25
VP_RC_VERIFICATION_FAILED = 26
VP_RC_NO_SUCH_SESSION = 27

VPReturnCodes = [
	"VP_RC_SUCCESS", "VP_RC_VERSION_MISMATCH", "VP_RC_NOT_INITIALIZED", 
	"VP_RC_ALREADY_INITIALIZED", "VP_RC_STRING_TOO_LONG", 
	"VP_RC_INVALID_LOGIN", "VP_RC_WORLD_NOT_FOUND", 
	"VP_RC_WORLD_LOGIN_ERROR", "VP_RC_NOT_IN_WORLD", "VP_RC_CONNECTION_ERROR",
	"VP_RC_NO_INSTANCE", "VP_RC_NOT_IMPLEMENTED", "VP_RC_NO_SUCH_ATTRIBUTE", 
	"VP_RC_NOT_ALLOWED", "VP_RC_DATABASE_ERROR", "VP_RC_NO_SUCH_USER", 
	"VP_RC_TIMEOUT", "VP_RC_NOT_IN_UNIVERSE", "VP_RC_INVALID_ARGUMENTS", 
	"VP_RC_OBJECT_NOT_FOUND", "VP_RC_UNKNOWN_ERROR", "VP_RC_RECURSIVE_WAIT", 
	"VP_RC_JOIN_DECLINED", "VP_RC_SECURE_CONNECTION_REQUIRED", 
	"VP_RC_HANDSHAKE_FAILED", "VP_RC_VERIFICATION_FAILED", 
	"VP_RC_NO_SUCH_SESSION" ]
